[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fallback_oz = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[profile.default.zksync]
enable_eravm_extensions = true

[rpc_endpoints]
abstractTestnet = "https://api.testnet.abs.xyz"
abstractMainnet = "https://api.mainnet.abs.xyz"

[etherscan]
abstractTestnet = { chain = "11124", url = "https://api.etherscan.io/v2/api?chainid=11124", key = "${ETHERSCAN_API_KEY}" }
abstractMainnet = { chain = "2741", url = "https://api.etherscan.io/v2/api?chainid=2741", key = "${ETHERSCAN_API_KEY}" }
